name = "BasicNumberTheory"
version = "0.1.0"
defaultTargets = ["basicnumbertheory"]

[[lean_lib]]
name = "BasicNumberTheory"

[[lean_exe]]
name = "basicnumbertheory"
root = "Main"

[[dependency]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.23.0" 
